### ISSUE TITLE
Check and Format buttons keep processing 

### ISSUE THREAD

**Issue by mmahmoudlibert-nettt** [aiken-lang/play#1]
After running a check both buttons check and format keep showing processing:

![image](https://github.com/aiken-lang/play/assets/95937905/a98f8dbd-780d-457e-a515-164165db64e6)

Checking the console log I was able to notice this error:
![image](https://github.com/aiken-lang/play/assets/95937905/fc384568-972b-44c1-98e5-6921770e1ead)

A link to playground: https://play.aiken-lang.org?code=G4sKAIzDOIZ8MZVNHPNzKv7OMr10IxGcUnFJLVMbz-38QwrWN6RYFg2ikMLSL9fe8d_X6Wrbt9lkJjko4CdyVafKyRYILbCwwMKK6hCnWwVKsFu32y_fnlHbD3ZpMwWWfokov9rZNtxD4Xk9n-I8dquhra0d5fptaWymdVrS881_HQqdlFJ9EKn8jeuVu2wiAXH9Ilhf52DOREPPAmdxwqTH4bwO31_qRBnrv81EXaVTvsxE6QS8LnkieUyFuzvcdKrI_LW0HbljF2z9OQ4OQoaPabFMreP55DueCr32c-RIC22M5gU8NW46xavyMWGynFbydzypooFCQCdLcy3JjOOye_6cfYqHHJlX6xyP__SGNzdNBBPYMTWjg9x1PeQfL58a6AXaR3AdS3HiowkFlhY3NhYTM2lGhzERmD-1ghkuIEfPmNZCkjFOp8AHvUMt_AHuEJFZt21nYBA2wbczwwyr6v_DZOyuoJLDL_YO5l8fE-qMxZqzE0LBnBg4XqC04c_Yy0RpvXQ6DJ_ULDbOq_PPXlVoENFelw4C6xbEfPxSAQvVtaQNf9qWyU-3eQVJIumgJyEaU-AEhVUURn6xDYiET5piHP_WesaIsXTRk99qPzKKXZbCDTTYtuyVNjVJSzToUI-J4GCjdWzpnbxKPmvWYe5yh91Led0LYFdsj5DEVxIPv_NyZX4NqSiW90AqINyHBLYNTQSQpjjxOPJEiIoqPvO8UyaMrVAIrNyZkGrXbkqIxVAclxV6lzymkl3rkwPWaDWEouMfbTOM2vNo60_r-SnSiSSlvLFUUukNf3UREVvaPVIsTpqH4u5e0kz3N_BZUq9ASTA2fjDEkyjWcokl61agjbQVOO8D4E_-0qpKUUTlFCmvBDUGlMxMVigQoqzIwKwGk_FKkTaJ4VrUUzQBPFuipwHb88nNBhJpPCsBG-8DmxqYd7LJRnYY2c13E4hF_yk0-tohPMk_WSZllbFJpAOY5xTGZu-2eJ60uYTy4QRFa_FyFhcQyd-1DogK_ONAw68j20fQAR4DaRoqxQxqk-Ymm1iy-tOkgvmAEC7Dg9chR4lQKBVttgERLtNb15HnGlNPOQpy3W7KYIgsZDKbOdUlZ8odGYp5RmtYXfgdC0sj-xBhmz1D-fpjOOnsSZSDS14BOXnjrN-lPHxxDMsViHmEk3rfC5C3uIUfAtcgsEFSuZxtpChDz14RAQ

This is just a part of the validator source code, the remaining will be added as I keep resolving issues.

**Comment by rvcas** [comment]
I'll see if bumping to v1.0.10 helps

**Comment by rvcas** [comment]
found the issue
